name: huskyclient
description: >- 
  dart husky client library for ebox.
  currently only dart native is supported. but vpn version is under workiing.
version: 0.0.4
homepage: http://gitlab.etsus.net/dart/huskyclient

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  fixnum: ^0.10.11
  meta: ^1.2.4
  protobuf: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
